import Room1 from "./images/Room1.jpg";
import Room2 from "./images/Room2.jpg";
import Room3 from "./images/Room3.jpg";
import Room4 from "./images/Room4.jpg";
import Room5 from "./images/Room5.jpg";
import Room6 from "./images/Room6.jpg";
import Room7 from "./images/Room7.jpg";
import Room8 from "./images/Room8.jpg";
import Room9 from "./images/Room9.jpg";
import Room10 from "./images/Room10.jpg";
import Room11 from "./images/Room11.jpg";
import Room12 from "./images/Room12.jpg";
import Room13 from "./images/Room13.jpg";
import Room14 from "./images/Room14.jpg";
import Room15 from "./images/Room15.jpg";
import Room16 from "./images/Room16.jpg";

const apartemntsData = [
  {
    id: 1,
    image: Room1,
    title: "Apartment",
    type: "Regular room",
    pets: false,
    brekfast: false,
    price: "100$",
    guests: 1,
    desc: "Single Room",
    city: "Split",
  },
  {
    id: 2,
    image: Room4,
    title: "Apartment",
    type: "Modern room",
    pets: false,
    brekfast: true,
    price: "250$",
    guests: 2,
    desc: "2 Rooms Apartment",
  },
  {
    id: 3,
    image: Room2,
    title: "Apartment",
    type: "Regular room",
    pets: false,
    brekfast: false,
    price: "200$",
    guests: 1,
    desc: "Single Room",
  },

  {
    id: 4,
    image: Room3,
    title: "Apartment",
    type: "Modern room",
    pets: true,
    brekfast: false,
    guests: 2,
    price: "250$",
    desc: "2 Rooms Apartment",
  },

  {
    id: 5,
    image: Room5,
    title: "Apartment",
    type: "Exclusive",
    pets: true,
    brekfast: true,
    price: "300$",
    guests: 4,
    desc: "Luxury Room",
  },
  {
    id: 6,
    image: Room6,
    title: "Apartment",
    type: "Regular room",
    pets: false,
    brekfast: false,
    price: "150$",
    guests: 1,
    desc: "Single Room",
  },
  {
    id: 7,
    image: Room7,
    title: "Apartment",
    type: "Regular room",
    pets: true,
    brekfast: false,
    price: "100$",
    guests: 1,
    desc: "Single Room",
  },
  {
    id: 8,
    image: Room8,
    title: "Apartment",
    type: "Modern room",
    pets: false,
    brekfast: true,
    price: "200$",
    guests: 2,
    desc: "2 Rooms Apartment",
  },
  {
    id: 9,
    image: Room9,
    title: "Apartment",
    type: "Modern room",
    pets: true,
    brekfast: false,
    price: "250$",
    guests: 2,
    desc: "2 Rooms Apartment",
  },
  {
    id: 10,
    image: Room10,
    title: "Apartment",
    type: "Regular room",
    pets: true,
    brekfast: true,
    price: "550$",
    guests: 4,
    desc: "Luxury Room",
  },
  {
    id: 11,
    image: Room11,
    title: "Apartment",
    type: "Exclusive",
    pets: true,
    brekfast: true,
    price: "350$",
    guests: 3,
    desc: "Luxury Room",
  },
  {
    id: 12,
    image: Room12,
    title: "Apartment",
    type: "Regular room",
    pets: false,
    brekfast: false,
    price: "100$",
    guests: 1,
    desc: "Single Room",
  },
  {
    id: 13,
    image: Room13,
    title: "Apartment",
    type: "Modern room",
    pets: false,
    brekfast: true,
    price: "250$",
    guests: 2,
    desc: "2 Rooms Apartment",
  },
  {
    id: 14,
    image: Room14,
    title: "Apartment",
    type: "Exclusive",
    pets: true,
    brekfast: true,
    price: "500$",
    guests: 2,
    desc: "Luxury Room",
  },
  {
    id: 15,
    image: Room15,
    title: "Apartment",
    type: "Modern room",
    pets: true,
    brekfast: false,
    price: "250$",
    guests: 3,
    desc: "2 Rooms Apartment",
  },
  {
    id: 16,
    image: Room16,
    title: "Apartment",
    type: "Exclusive",
    pets: true,
    brekfast: true,
    price: "550$",
    guests: 4,
    desc: "Luxury Room",
  },
];

export default apartemntsData;
